//just all the classes used in the program
//easier because makefile will saythe same
//add all the .cpp files here here
#include "Races.cpp"
#include "EuropeanRace.cpp"
#include "NonEuropeanRace.cpp"
#include "SoftTyre.cpp"
#include "MediumTyre.cpp"
#include "HardTyre.cpp"
#include "Tyres.cpp"
#include "RacingTyres.cpp"
#include "RacingStrategy.cpp"
#include "RiskyStrategy.cpp"
#include "Sticker.cpp"
#include "Sponsor.cpp"
#include "DriverNumber.cpp"
#include "DefaultStrategy.cpp"
#include "RainyStrategy.cpp"
#include "OwnStrategy.cpp"
#include "CarEngine.cpp"
#include "BDWEngine.cpp"
#include "DerarriEngine.cpp"
#include "Car.cpp"
#include "Sensors.cpp"
#include "TyreSensor.cpp"
#include "FuelSensor.cpp"
#include "Engineer.cpp"
#include "Aerodynamics.cpp"
#include "Chasis.cpp"
#include "Engine.cpp"
#include "Electronics.cpp"
